# Optimized Netlify Configuration for SEO and Performance
# Enhanced configuration for better search engine visibility

[build]
  publish = "."
  command = "echo 'Static site deployment - no build process required'"

# Enhanced security and SEO headers
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Content-Security-Policy = "default-src 'self'; script-src 'self' 'unsafe-inline' https://cdn.tailwindcss.com; style-src 'self' 'unsafe-inline' https://fonts.googleapis.com https://cdn.tailwindcss.com; font-src 'self' https://fonts.gstatic.com; img-src 'self' data: https:;"
    X-Robots-Tag = "index, follow"
    
# Cache optimization for static assets
[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/js/*"
  [headers.values]
    Cache-Control = "public, max-age=86400"

[[headers]]
  for = "/*.css"
  [headers.values]
    Cache-Control = "public, max-age=86400"

# SEO files optimization
[[headers]]
  for = "/sitemap.xml"
  [headers.values]
    Content-Type = "application/xml"
    Cache-Control = "public, max-age=3600"

[[headers]]
  for = "/rss.xml"
  [headers.values]
    Content-Type = "application/rss+xml"
    Cache-Control = "public, max-age=3600"

[[headers]]
  for = "/feed.json"
  [headers.values]
    Content-Type = "application/feed+json"
    Cache-Control = "public, max-age=3600"

[[headers]]
  for = "/robots.txt"
  [headers.values]
    Content-Type = "text/plain"
    Cache-Control = "public, max-age=86400"

[[headers]]
  for = "/manifest.json"
  [headers.values]
    Content-Type = "application/manifest+json"
    Cache-Control = "public, max-age=86400"

# SEO redirects for common search terms
[[redirects]]
  from = "/cgpa-calculator"
  to = "/"
  status = 301
  force = true

[[redirects]]
  from = "/gpa-calculator"
  to = "/"
  status = 301
  force = true

[[redirects]]
  from = "/bangladesh-cgpa"
  to = "/"
  status = 301
  force = true

[[redirects]]
  from = "/du-cgpa-calculator"
  to = "/"
  status = 301
  force = true

[[redirects]]
  from = "/buet-gpa-calculator"
  to = "/"
  status = 301
  force = true

[[redirects]]
  from = "/nsu-cgpa"
  to = "/"
  status = 301
  force = true

[[redirects]]
  from = "/brac-university-gpa"
  to = "/"
  status = 301
  force = true
