# Netlify Build Configuration for SEO Optimization
# Clean and Error-Free Version

[build]
  # Build command (for static site)
  command = "echo 'Static site - no build required'"
  
  # Publish directory (update if your output folder is different, e.g. "public")
  publish = "."

  # Build environment variables
  [build.environment]
    NODE_ENV = "production"
    HUGO_VERSION = "0.118.2"

# ------------------------------
# SEO and Performance Plugins
# ------------------------------

[[plugins]]
  # Sitemap generator
  package = "@netlify/plugin-sitemap"
  
  [plugins.inputs]
    buildDir = "."
    exclude = [
      "/_headers",
      "/_redirects", 
      "/netlify.toml",
      "/README.md",
      "/SEO-Guide.md"
    ]
    trailingSlash = false
    prettyURLs = true

[[plugins]]
  # Robots.txt generator
  package = "@netlify/plugin-robots-txt"

  [plugins.inputs]
    policy = [
      { userAgent = "*", allow = "/" }
    ]
    sitemap = "https://bdcgpacalculator.netlify.app/sitemap.xml"
    host = "https://bdcgpacalculator.netlify.app"

[[plugins]]
  # Optimize images automatically
  package = "netlify-plugin-image-optim"

[[plugins]]
  # Minify HTML, CSS, JS
  package = "netlify-plugin-minify-html"
  
  [plugins.inputs]
    contexts = ["production"]

[[plugins]]
  # Prerender pages for better SEO
  package = "netlify-plugin-prerender-spa"
  
  [plugins.inputs]
    routes = ["/", "/cgpa-calculator", "/gpa-calculator"]

# ------------------------------
# Security + SEO Headers
# ------------------------------

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Link = "<https://bdcgpacalculator.netlify.app/>; rel=\"canonical\""

# Production-specific headers
[context.production.headers]
  for = "/*"
  [context.production.headers.values]
    X-Robots-Tag = "index, follow"
    Cache-Control = "public, max-age=3600"

# Preview and Branch Deploy headers
[context.deploy-preview.headers]
  for = "/*"
  [context.deploy-preview.headers.values]
    X-Robots-Tag = "noindex, nofollow"

[context.branch-deploy.headers]
  for = "/*"
  [context.branch-deploy.headers.values]
    X-Robots-Tag = "noindex, nofollow"

# ------------------------------
# Build Processing
# ------------------------------

[build.processing]
  skip_processing = false

[build.processing.css]
  bundle = true
  minify = true

[build.processing.js]
  bundle = true
  minify = true

[build.processing.html]
  pretty_urls = true

[build.processing.images]
  compress = true

# ------------------------------
# Redirect Rules for SEO
# ------------------------------

[[redirects]]
  from = "/cgpa-calculator"
  to = "/"
  status = 301
  force = true

[[redirects]]
  from = "/gpa-calculator"
  to = "/"
  status = 301
  force = true

# ------------------------------
# Environment-specific settings
# ------------------------------

[context.production.environment]
  HUGO_ENV = "production"

[context.deploy-preview.environment]
  HUGO_ENV = "staging"
